### PR TITLE
Add exec constraints to local Java runtime toolchains

### PR DESCRIPTION
**Pull request by fmeum**
Fixes incorrect behavior in cross-platform build situations where a local Java runtime would end up in the runfiles of a `java_binary` target built for a platform on which it can't be executed.

Work towards https://github.com/bazelbuild/bazel/issues#18265
Split off from https://github.com/bazelbuild/bazel/pull/18262

### CODE REVIEW

**Comment by fmeum** [comment]
@comius @hvadehra Could you review this PR?

**Comment by fmeum** [comment]
@hvadehra Could you also review this? It's a follow-up to https://github.com/bazelbuild/rules_java/pull/114 and the last part of https://github.com/bazelbuild/bazel/pull/18262 that affects rules_java.

**Review by hvadehra — APPROVED** [review]

**Comment by fmeum** [comment]
@hvadehra Without #114, this PR in isolation may result in Android compilation failures when Bazel is updated to use a java_tools version. Do you already know whether #114 can be merged soon?

**Comment by hvadehra** [comment]
Yeah, there was an issue with the import, I'm trying to get it to work.

**Pull request merged**
