### PR TITLE
Add s390x support in JDK 8 and JDK 17 toolchain

### PR DESCRIPTION
**Pull request by kun-lu20**
Since commit https://github.com/bazelbuild/bazel/commit/66f571e8b5ad35dd129afbe875f7e9f919f32612 has added support for JDK 11, 17 and 19 on cpu s390x in `bazel` repo and `bzlmod` uses `rules_java`,  this PR aims to add s390x support for JDK 8 and JDK 17 toolchain in `rules_java` repo.

Signed-off-by: Kun-Lu <kun.lu@ibm.com>

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @comius ,

Sorry for the delay. This PR was raised as per your comment [here](https://github.com/bazelbuild/bazel/pull/17382#issuecomment-1453089789).

Could you please review this PR? Thanks!

**Comment by kun-lu20** [comment]
Hi @comius ,

Could you please review this PR when you have a chance? Thank you very much!

**Comment by kun-lu20** [comment]
Hi @comius ,

Could you please take a look at this PR? 

Thank you very much!

**Comment by kun-lu20** [comment]
Since `remotejdk_17` is now the [default java_toolchain configuration](https://github.com/bazelbuild/rules_java/blob/b9a576aa60becaa87de97e039f4a06cc2b1cdfac/toolchains/default_java_toolchain.bzl#L94) in `rules_java`, and PR https://github.com/bazelbuild/rules_java/pull/110 has added `remotejdk17_linux_s390x` repo, this PR was updated to register `remotejdk17_linux_s390x` toolchain, so that `bzlmod` can be smoothly enabled on s390x cpu.

This PR also added `remote_jdk8_linux_s390x` toolchain, it would be great if community could consider to upload the corresponding JDK tar ball to Bazel's mirror site as well.

Hi @hvadehra , could you please take a look at this PR when you have a chance? Thank you very much!

**Comment by kun-lu20** [comment]
Hi @meteorcloudy ,

Could you please review this PR? Thank you very much!

**Review by hvadehra — APPROVED** [review]

**Comment by kun-lu20** [comment]
Thanks @hvadehra !

**Pull request merged**
