### PR TITLE
Fix skylib dependency

### PR DESCRIPTION
**Pull request by comius**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Is `bazel_skylib` a dev dependency or not? If it is, we probably want to keep it as dev dependency and not build all targets like `@rules_java//...`?

**Comment by meteorcloudy** [comment]
Can you also add 
```
    "repository": [
        "github:bazelbuild/rules_java"
    ],
```
in https://github.com/bazelbuild/rules_java/blob/master/.bcr/metadata.template.json?

**Comment by comius** [comment]
> Is `bazel_skylib` a dev dependency or not? If it is, we probably want to keep it as dev dependency and not build all targets like `@rules_java//...`?

It's used in `java/BUILD` and `java/private/BUILD`, so it's not a dev dependency.

**Comment by comius** [comment]
> Can you also add
> 
> ```
>     "repository": [
>         "github:bazelbuild/rules_java"
>     ],
> ```
> 
> in https://github.com/bazelbuild/rules_java/blob/master/.bcr/metadata.template.json?

Done

**Review by meteorcloudy — APPROVED** [review]

**Comment by comius** [comment]
> > Can you also add
> > ```
> >     "repository": [
> >         "github:bazelbuild/rules_java"
> >     ],
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in https://github.com/bazelbuild/rules_java/blob/master/.bcr/metadata.template.json?
> 
> Done

I think this has broken bcr publish app. :(

**Pull request merged**
