### PR TITLE
Update JDK 21 binaries

### PR DESCRIPTION
**Pull request by fmeum**
Also switch to Zulu for Windows ARM64.

### CODE REVIEW

**Comment by hvadehra** [comment]
I think you need to drop L93 in java/bazel/repositories_util.bzl

**Comment by fmeum** [comment]
@hvadehra Thanks, done!

**Comment by fmeum** [comment]
I sent https://github.com/bazelbuild/bazel/issues/23650 to mirror the new URLs.

**Comment by fmeum** [comment]
@hvadehra CI is green now

**Comment by hvadehra** [comment]
Thanks a lot for improving the test :)

**Review by hvadehra — APPROVED** [review]

**Pull request closed without merging**
